[general]
framerate = 90
sensitivity = 120
bars = 80

[input]
method = pulse
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
channels = stereo
mono_option = average
reverse = 0

[smoothing]
noise_reduction = 15

;[eq]
;1 = 1.5
;2 = 1.4
;3 = 1.3
;4 = 1.2
;5 = 1.1
;6 = 1.0
;7 = 0.9
;8 = 0.8
;9 = 0.7
;10 = 0.6